(length (list 9 8 7 6))
(length (list (list 7 8 9)))
(length (list))
(length 7)
(length (cons 1 2))
(length ())
(length (cdr (cdr (list 1 2))))
(length x)
(length () x)
(length () ())
(length (list () () () () ))
(length (list #f #f #f #f #f))
(length (list 0 0 0 0 0 0))
(length)
(length (cons 1 (cons 2 3)))
(define length 4)
(* length 1)
(length (list 9 8 7 6))
