(begin (define y 2) (define (square x) (* x x)) (square 2))
(begin (define x (cons 1 ())) (car x))
(begin (define z (append x x)) (car z))
(square (+ y y y))
(begin list list-ref cons car cdr)
(begin (define (foo bar) (lambda (x y) (- bar x y))) (define bar 7) (define something (foo 6)) (list (something 2 3) ((foo 9) 8 7)))
((foo 9) 8 7)
((foo (square 3)) 8 7)
(begin (define a 3) (define a (+ a 1)))
((begin (define a 3) (define a (+ a 1))))
(begin)
