(define x (list 1 -1 -3 -2))
(filter (lambda (x) (> x 0)) x)
x
(filter (lambda (x) (or (> x 0) (< x 0))) (list 1 1 1 1 0 0 0 -1 -1 -1 -1))
(filter (lambda (x) #t) (list 1 1 1 1 0 0 0 -1 -1 -1 -1))
(filter (lambda (x) (or (> x 0) (< x 0))) ())
(filter (lambda (x) (or (> x 0) (< x 0))) (list))
(define (!= x y) (not (equal? x y)))
(define (nonzero? x) (!= x 0))
(define (zero? x) (equal? x 0))
(define (nonzero-vals list_) (filter nonzero? list_))
(define (zero-vals list_) (filter zero? list_))
(nonzero-vals (list -1 0.0 1 2 3 0 4))
(zero-vals (list -1 0.0 1 2 3 0 4))
