()
(if (equal? () ()) 1 0)
(if (equal? () #f) 1 0)
(if (equal? () #t) 1 0)
(if (equal? () 1) 1 0)
(if (equal? () 0) 1 0)
(cons 1 (cons 2 (cons 3 (cons 4 ()))))
(list 1 2 3 4)
(list 1)
(list)
(list () () ())
(list (list 1 2) (cons 3 4) (list))
(define (foo bar) (lambda (x y) (- bar x y)))
(define bar 7)
(define something (foo 10))
(list (something 2 3) ((foo 9) 8 7))
(if (equal? () (list) (cdr (list 1))) (list 1) ())
(if #t () (list 0))
(if #f () (list 0))
((cons 1 2))
((list 1 2 3))
(())
(car (list))
((car (list 1)))
(cdr (cdr (list 1)))
(define list +)
(list 1 2 3 4)
